import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion, useScroll, useTransform, AnimatePresence } from 'framer-motion';
import { ArrowRight, Mic, Brain, Code2, FileText, BarChart3, Trophy, Check, Sparkles, ChevronDown, Play } from 'lucide-react';
import { Logo } from '../components/ui';

/* ─── Data ────────────────────────────────────────────────────────────── */
const FEATURES = [
  { icon: Mic,       title: 'Voice AI Interviewer',    desc: 'Real voice interaction with instant transcription and confidence analysis.', color: 'from-indigo-500 to-purple-600' },
  { icon: Brain,     title: 'Adaptive Question Engine', desc: 'GPT-4o generates questions tailored to your resume and experience level.', color: 'from-indigo-600 to-cyan-500' },
  { icon: Code2,     title: 'Live Code Editor',         desc: 'Monaco-powered editor with multi-language support and hidden test cases.', color: 'from-emerald-500 to-teal-500' },
  { icon: FileText,  title: 'Resume AI Analysis',       desc: 'Deep ATS scoring, skill extraction, and gap analysis from your resume.', color: 'from-orange-500 to-amber-500' },
  { icon: BarChart3, title: 'Performance Analytics',    desc: 'Track progress with detailed charts and AI improvement roadmaps.', color: 'from-cyan-500 to-rose-500' },
  { icon: Trophy,    title: 'Leaderboard & Streaks',    desc: 'Compete with peers, maintain streaks, and unlock achievements.', color: 'from-yellow-500 to-orange-500' },
];

const PRICING = [
  { plan: 'Free',       price: '$0',  period: '/month', features: ['5 interviews/month', 'HR & Behavioral modes', 'Basic feedback', 'Community access'], cta: 'Get Started',     highlight: false },
  { plan: 'Pro',        price: '$19', period: '/month', features: ['Unlimited interviews', 'All 4 interview modes', 'Voice AI interviewer', 'Resume analyzer', 'Detailed AI feedback', 'Coding round + editor', 'Priority support'], cta: 'Start Free Trial', highlight: true },
  { plan: 'Enterprise', price: '$49', period: '/month', features: ['Everything in Pro', 'Team management', 'Custom questions', 'API access', 'SSO', 'Dedicated support'], cta: 'Contact Sales',  highlight: false },
];

const FAQS = [
  { q: 'How does the AI interview work?',       a: 'Our AI uses GPT-4o to generate role-specific questions, respond to your answers in real-time, and provide detailed feedback covering technical accuracy, communication, and confidence.' },
  { q: 'Can I use voice input?',                a: 'Yes! We use the Web Speech API for real-time speech-to-text. The AI reads questions aloud and you can respond by voice, with live transcript displayed on screen.' },
  { q: 'What interview types are supported?',   a: 'HR, DSA/Algorithms, System Design, Behavioral (STAR method), and Live Coding with our Monaco editor — all with AI evaluation.' },
  { q: 'How accurate is the AI feedback?',      a: 'Feedback is generated by GPT-4o with specialized prompts for each interview mode. It covers scores, strengths, weaknesses, and a personalised improvement roadmap.' },
];

const STATS = [['50K+', 'Interviews Conducted'], ['94%', 'Success Rate'], ['4.9★', 'User Rating'], ['120+', 'Companies Covered']];

/* ─── Floating Particle ────────────────────────────────────────────────── */
const Particle = ({ style }) => (
  <motion.div
    className="absolute rounded-full pointer-events-none"
    style={style}
    animate={{ y: [0, -30, 0], opacity: [0.15, 0.4, 0.15], scale: [1, 1.2, 1] }}
    transition={{ duration: style.duration, repeat: Infinity, delay: style.delay, ease: 'easeInOut' }}
  />
);

/* ─── FAQ Item ─────────────────────────────────────────────────────────── */
const FAQItem = ({ q, a, i }) => {
  const [open, setOpen] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ delay: i * 0.06 }}
      className="bg-white border border-slate-200/80 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300"
    >
      <button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between px-6 py-5 text-left gap-4 group">
        <span className="font-semibold text-[15px] text-slate-800 group-hover:text-accent transition-colors">{q}</span>
        <motion.div animate={{ rotate: open ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown size={18} className="text-slate-400 flex-shrink-0" />
        </motion.div>
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
          >
            <div className="px-6 pb-5 text-[13.5px] text-slate-500 leading-relaxed border-t border-slate-100 pt-4 bg-slate-50/50">{a}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

/* ─── Landing Page ─────────────────────────────────────────────────────── */
const Landing = () => {
  const heroRef = useRef(null);
  const { scrollY } = useScroll();
  const heroY       = useTransform(scrollY, [0, 400], [0, -40]);

  /* Generate fixed particles for the purple background area */
  const particles = Array.from({ length: 18 }, (_, i) => ({
    width:    `${4 + (i % 4) * 3}px`,
    height:   `${4 + (i % 4) * 3}px`,
    left:     `${(i * 37) % 100}%`,
    top:      `${(i * 47) % 80}%`, // keep it in the top hero portion
    background: i % 2 === 0 ? 'rgba(255,255,255,0.3)' : 'rgba(6,182,212,0.4)',
    duration: 5 + (i % 5),
    delay:    i * 0.4,
  }));

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-850 overflow-x-hidden">

      {/* ── Slanted Purple Hero Background (Practipago-style) ── */}
      <div 
        className="absolute inset-x-0 top-0 h-[92vh] bg-gradient-to-br from-indigo-600 via-indigo-700 to-purple-800 -z-10 shadow-lg"
        style={{ clipPath: 'polygon(0 0, 100% 0, 100% 70%, 0 88%)' }}
      />

      {/* ── Ambient Glow Orbs for Hero ── */}
      <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
        <motion.div
          animate={{ scale: [1, 1.1, 1], opacity: [0.15, 0.3, 0.15] }}
          transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
          className="absolute -top-40 -left-40 w-[600px] h-[600px] bg-cyan-300 rounded-full blur-[120px]"
        />
      </div>

      {/* ── Floating Particles in Hero Banner ── */}
      <div className="absolute inset-0 h-[90vh] z-0 pointer-events-none overflow-hidden">
        {particles.map((p, i) => <Particle key={i} style={p} />)}
      </div>

      {/* ══════════════════════════════════════════════════════════
          NAV
      ══════════════════════════════════════════════════════════ */}
      <motion.nav
        initial={{ y: -80, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.6, ease: 'easeOut' }}
        className="relative z-10 flex items-center justify-between px-8 py-5 border-b border-white/10 bg-white/5 backdrop-blur-md"
      >
        <Logo size={32} subtext="AI Interview Coach" textClassName="text-white" />
        <div className="hidden md:flex items-center gap-8 text-sm text-white/70">
          {['Features', 'Pricing', 'FAQ'].map((item) => (
            <a key={item} href={`#${item.toLowerCase()}`}
              className="relative hover:text-white transition-colors duration-200 group">
              {item}
              <span className="absolute -bottom-0.5 left-0 w-0 h-px bg-cyan-300 group-hover:w-full transition-all duration-300" />
            </a>
          ))}
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login" className="text-sm text-white/70 hover:text-white transition-colors px-3 py-2">Sign in</Link>
          <Link to="/register"
            className="flex items-center gap-2 bg-cyan-400 hover:bg-cyan-300 text-slate-900 text-sm font-semibold px-5 py-2.5 rounded-xl transition-all shadow-md shadow-cyan-400/10 hover:shadow-cyan-400/25 hover:-translate-y-0.5">
            Get Started <ArrowRight size={14} />
          </Link>
        </div>
      </motion.nav>

      {/* ══════════════════════════════════════════════════════════
          HERO
      ══════════════════════════════════════════════════════════ */}
      <motion.section
        ref={heroRef}
        style={{ y: heroY }}
        className="relative z-10 min-h-[82vh] flex flex-col items-center justify-center text-center px-6 pt-10 pb-24 text-white"
      >
        {/* Badge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="inline-flex items-center gap-2 px-5 py-2 rounded-full border border-white/20 bg-white/10 backdrop-blur-md text-sm text-cyan-300 mb-8"
        >
          <motion.span animate={{ rotate: [0, 15, -15, 0] }} transition={{ duration: 2, repeat: Infinity, delay: 1 }}>
            <Sparkles size={14} className="text-cyan-300" />
          </motion.span>
          AI-Powered Interview Preparation Platform
        </motion.div>

        {/* Headline */}
        <div className="max-w-5xl mx-auto mb-6">
          {['Ace Every Interview', 'with AI Coaching'].map((line, li) => (
            <div key={li} className="overflow-hidden">
              <motion.div
                initial={{ y: 60, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 0.7, delay: 0.3 + li * 0.15, ease: [0.25, 0.46, 0.45, 0.94] }}
              >
                <h1 className="font-heading text-5xl md:text-7xl font-black leading-[1.05] tracking-tight">
                  {li === 0 ? line : (
                    <>with{' '}
                      <span className="relative inline-block text-cyan-300">
                        <span>AI Coaching</span>
                        {/* Underline glow */}
                        <motion.span
                          initial={{ scaleX: 0 }}
                          animate={{ scaleX: 1 }}
                          transition={{ duration: 0.6, delay: 1.1 }}
                          className="absolute -bottom-1 left-0 right-0 h-1 rounded-full bg-cyan-400 origin-left"
                        />
                      </span>
                    </>
                  )}
                </h1>
              </motion.div>
            </div>
          ))}
        </div>

        {/* Subtitle */}
        <motion.p
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.7, duration: 0.5 }}
          className="text-lg md:text-xl text-white/80 max-w-2xl mx-auto mb-10 leading-relaxed"
        >
          Practice HR, DSA, System Design &amp; Behavioral interviews with a real-time AI interviewer.
          Get instant feedback, scores, and a personalised improvement roadmap.
        </motion.p>

        {/* CTA buttons */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.9, duration: 0.5 }}
          className="flex items-center justify-center gap-4 flex-wrap mb-16"
        >
          <Link to="/register"
            className="group flex items-center gap-2.5 bg-cyan-400 hover:bg-cyan-350 text-slate-900 font-bold px-8 py-4 rounded-2xl text-[16px] transition-all shadow-xl shadow-cyan-400/20 hover:shadow-cyan-400/35 hover:-translate-y-1">
            Start Practicing Free
            <motion.span animate={{ x: [0, 4, 0] }} transition={{ duration: 1.2, repeat: Infinity }}>
              <ArrowRight size={18} />
            </motion.span>
          </Link>
          <Link to="/login"
            className="flex items-center gap-2 bg-white/10 border border-white/20 hover:bg-white/20 text-white font-semibold px-8 py-4 rounded-2xl text-[16px] transition-all backdrop-blur-sm">
            <Play size={15} className="text-cyan-300 fill-cyan-300" /> Watch Demo
          </Link>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.1, duration: 0.6 }}
          className="flex flex-wrap justify-center gap-10 md:gap-16"
        >
          {STATS.map(([val, label], i) => (
            <motion.div
              key={label}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.2 + i * 0.1 }}
              className="text-center group"
            >
              <div className="font-heading text-3xl font-extrabold text-white group-hover:text-cyan-300 transition-colors duration-300">{val}</div>
              <div className="text-xs text-white/60 mt-1 tracking-wide">{label}</div>
            </motion.div>
          ))}
        </motion.div>

        {/* Scroll indicator */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.6 }}
          className="absolute bottom-6 left-1/2 -translate-x-1/2"
        >
          <motion.div
            animate={{ y: [0, 6, 0] }}
            transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
            className="flex flex-col items-center gap-1 text-white/40"
          >
            <span className="text-[10px] tracking-widest uppercase">Scroll</span>
            <ChevronDown size={16} />
          </motion.div>
        </motion.div>
      </motion.section>

      {/* ══════════════════════════════════════════════════════════
          FEATURES
      ══════════════════════════════════════════════════════════ */}
      <section id="features" className="relative z-10 py-16 px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-xs text-slate-500 mb-4 uppercase tracking-widest font-semibold">
            What We Offer
          </div>
          <h2 className="font-heading text-4xl font-extrabold text-slate-900 mb-3">Everything You Need to Win</h2>
          <p className="text-slate-500 max-w-xl mx-auto">One platform, six powerful tools — built for modern engineering interviews.</p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
          {FEATURES.map(({ icon: Icon, title, desc, color }, i) => (
            <motion.div
              key={title}
              initial={{ opacity: 0, y: 20, scale: 0.98 }}
              whileInView={{ opacity: 1, y: 0, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.08, duration: 0.5 }}
              whileHover={{ y: -6, scale: 1.01 }}
              className="relative group rounded-2xl p-6 bg-white border border-slate-200/60 shadow-sm overflow-hidden cursor-default transition-all duration-300 hover:border-indigo-200 hover:shadow-md hover:bg-slate-50/30"
            >
              {/* Card glow on hover */}
              <div className={`absolute -inset-px rounded-2xl bg-gradient-to-br ${color} opacity-0 group-hover:opacity-[0.04] transition-opacity duration-500 blur-xl`} />

              <div className={`relative w-12 h-12 rounded-2xl bg-gradient-to-br ${color} flex items-center justify-center mb-5 shadow-sm`}>
                <Icon size={20} className="text-white" />
              </div>
              <div className="relative font-heading font-bold text-[16px] text-slate-800 mb-2 group-hover:text-indigo-600 transition-colors">{title}</div>
              <div className="relative text-[13.5px] text-slate-500 leading-relaxed">{desc}</div>

              {/* Shimmer sweep */}
              <motion.div
                className="absolute inset-0 opacity-0 group-hover:opacity-100 pointer-events-none"
                style={{ background: 'linear-gradient(105deg, transparent 40%, rgba(99,102,241,0.03) 50%, transparent 60%)' }}
                animate={{ backgroundPositionX: ['200%', '-200%'] }}
                transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }}
              />
            </motion.div>
          ))}
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          PRICING
      ══════════════════════════════════════════════════════════ */}
      <section id="pricing" className="relative z-10 px-6 py-20 bg-slate-50/50 border-y border-slate-100">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-xs text-slate-500 mb-4 uppercase tracking-widest font-semibold">
            Pricing
          </div>
          <h2 className="font-heading text-4xl font-extrabold text-slate-900 mb-3">Simple, Transparent Pricing</h2>
          <p className="text-slate-500">Start free, upgrade when you're ready</p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {PRICING.map(({ plan, price, period, features, cta, highlight }, i) => (
            <motion.div
              key={plan}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              whileHover={{ y: -4 }}
              className={`relative rounded-2xl p-7 border transition-all duration-300 bg-white ${highlight
                ? 'border-indigo-400 bg-white shadow-xl shadow-indigo-500/5'
                : 'border-slate-200 hover:border-slate-350 hover:shadow-md'
              }`}
            >
              {highlight && (
                <>
                  <div className="absolute -inset-px rounded-2xl bg-gradient-to-br from-indigo-500/20 to-cyan-400/10 blur-xl -z-10" />
                  <div className="text-[10px] font-bold tracking-widest text-indigo-600 uppercase mb-4 flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-indigo-600 animate-pulse" />
                    Most Popular
                  </div>
                </>
              )}
              <div className="font-heading font-bold text-xl text-slate-800 mb-2">{plan}</div>
              <div className="flex items-end gap-1 mb-6">
                <span className="font-heading text-5xl font-extrabold text-slate-900">{price}</span>
                <span className="text-slate-400 text-sm pb-1.5">{period}</span>
              </div>
              <div className="space-y-3 mb-8">
                {features.map((f) => (
                  <div key={f} className="flex items-center gap-2.5 text-[13px]">
                    <div className={`w-4 h-4 rounded-full flex items-center justify-center flex-shrink-0 ${highlight ? 'bg-indigo-50' : 'bg-slate-50'}`}>
                      <Check size={10} className={highlight ? 'text-indigo-650 font-bold' : 'text-slate-400'} />
                    </div>
                    <span className="text-slate-600 font-medium">{f}</span>
                  </div>
                ))}
              </div>
              <Link
                to="/register"
                className={`block w-full text-center py-3 rounded-xl text-sm font-semibold transition-all shadow-sm ${highlight
                  ? 'bg-cyan-450 hover:bg-cyan-400 bg-cyan-400 text-slate-900 font-bold hover:shadow-md'
                  : 'bg-slate-50 border border-slate-200 hover:bg-slate-100 text-slate-700'
                }`}
              >
                {cta}
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          FAQ
      ══════════════════════════════════════════════════════════ */}
      <section id="faq" className="relative z-10 px-6 py-20 max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-xs text-slate-500 mb-4 uppercase tracking-widest font-semibold">
            FAQ
          </div>
          <h2 className="font-heading text-4xl font-extrabold text-slate-900">Frequently Asked Questions</h2>
        </motion.div>
        <div className="space-y-4">
          {FAQS.map(({ q, a }, i) => <FAQItem key={i} q={q} a={a} i={i} />)}
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          CTA BANNER (Rounded Purple Card style)
      ══════════════════════════════════════════════════════════ */}
      <section className="relative z-10 px-6 py-20 max-w-5xl mx-auto mb-16 overflow-hidden rounded-3xl bg-gradient-to-r from-indigo-600 via-indigo-700 to-purple-800 text-white shadow-xl shadow-indigo-600/10">
        {/* Decorative circle shapes inside CTA box */}
        <div className="absolute top-0 right-0 w-80 h-80 bg-cyan-500/10 rounded-full blur-[60px] pointer-events-none" />
        <div className="absolute -bottom-20 -left-20 w-80 h-80 bg-purple-500/10 rounded-full blur-[60px] pointer-events-none" />

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="relative text-center max-w-2xl mx-auto z-10"
        >
          <div className="inline-flex items-center gap-2 text-4xl mb-4">🚀</div>
          <h2 className="font-heading text-4xl md:text-5xl font-extrabold mb-4 leading-tight">
            Ready to land your<br />
            <span className="text-cyan-300">dream job?</span>
          </h2>
          <p className="text-indigo-100 opacity-90 mb-8 text-lg">Join 50,000+ engineers who've levelled up with InterviewAI Pro</p>
          <Link
            to="/register"
            className="inline-flex items-center gap-3 bg-cyan-400 hover:bg-cyan-300 text-slate-900 font-bold px-10 py-5 rounded-2xl text-[17px] transition-all shadow-xl shadow-cyan-400/20 hover:shadow-cyan-400/35 hover:-translate-y-1"
          >
            Start Free Interview
            <motion.span animate={{ x: [0, 4, 0] }} transition={{ duration: 1, repeat: Infinity }}>
              <ArrowRight size={20} />
            </motion.span>
          </Link>
        </motion.div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          FOOTER
      ══════════════════════════════════════════════════════════ */}
      <footer className="relative z-10 px-8 py-10 border-t border-slate-200 flex flex-col md:flex-row items-center justify-between gap-4 bg-white">
        <Logo size={28} subtext="Empowered Preparation" textClassName="text-slate-800" />
        <div className="flex gap-8 text-xs text-slate-500">
          {['Privacy', 'Terms', 'Contact'].map((item) => (
            <a key={item} href="#" className="hover:text-indigo-600 font-medium transition-colors">{item}</a>
          ))}
        </div>
        <div className="text-xs text-slate-400 font-medium">© 2025 InterviewAI Pro. All rights reserved.</div>
      </footer>
    </div>
  );
};

export default Landing;
