import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence, useScroll, useTransform } from 'framer-motion';
import { 
  ArrowRight, 
  Mic, 
  Brain, 
  Code2, 
  FileText, 
  BarChart3, 
  Trophy, 
  Check, 
  Sparkles, 
  ChevronDown, 
  Play,
  Volume2,
  Terminal,
  CheckCircle2,
  TrendingUp 
} from 'lucide-react';
import { Logo } from '../components/ui';

/* ─── Data ────────────────────────────────────────────────────────────── */
const FEATURES = [
  { icon: Mic,       title: 'Voice AI Interviewer',    desc: 'Real voice interaction with instant transcription and confidence analysis.', color: 'from-indigo-500 to-purple-600' },
  { icon: Brain,     title: 'Adaptive Question Engine', desc: 'GPT-4o generates questions tailored to your resume and experience level.', color: 'from-indigo-600 to-cyan-500' },
  { icon: Code2,     title: 'Live Code Editor',         desc: 'Monaco-powered editor with multi-language support and hidden test cases.', color: 'from-emerald-500 to-teal-500' },
  { icon: FileText,  title: 'Resume AI Analysis',       desc: 'Deep ATS scoring, skill extraction, and gap analysis from your resume.', color: 'from-orange-500 to-amber-500' },
  { icon: BarChart3, title: 'Performance Analytics',    desc: 'Track progress with detailed charts and AI improvement roadmaps.', color: 'from-cyan-500 to-rose-500' },
  { icon: Trophy,    title: 'Leaderboard & Streaks',    desc: 'Compete with peers, maintain streaks, and unlock achievements.', color: 'from-yellow-500 to-orange-500' },
];

const PRICING = [
  { plan: 'Free',       price: '$0',  period: '/month', features: ['5 interviews/month', 'HR & Behavioral modes', 'Basic feedback', 'Community access'], cta: 'Get Started',     highlight: false },
  { plan: 'Pro',        price: '$19', period: '/month', features: ['Unlimited interviews', 'All 4 interview modes', 'Voice AI interviewer', 'Resume analyzer', 'Detailed AI feedback', 'Coding round + editor', 'Priority support'], cta: 'Start Free Trial', highlight: true },
  { plan: 'Enterprise', price: '$49', period: '/month', features: ['Everything in Pro', 'Team management', 'Custom questions', 'API access', 'SSO', 'Dedicated support'], cta: 'Contact Sales',  highlight: false },
];

const FAQS = [
  { q: 'How does the AI interview work?',       a: 'Our AI uses GPT-4o to generate role-specific questions, respond to your answers in real-time, and provide detailed feedback covering technical accuracy, communication, and confidence.' },
  { q: 'Can I use voice input?',                a: 'Yes! We use the Web Speech API for real-time speech-to-text. The AI reads questions aloud and you can respond by voice, with live transcript displayed on screen.' },
  { q: 'What interview types are supported?',   a: 'HR, DSA/Algorithms, System Design, Behavioral (STAR method), and Live Coding with our Monaco editor — all with AI evaluation.' },
  { q: 'How accurate is the AI feedback?',      a: 'Feedback is generated by GPT-4o with specialized prompts for each interview mode. It covers scores, strengths, weaknesses, and a personalised improvement roadmap.' },
];

const STATS = [
  ['50K+', 'Interviews Conducted'], 
  ['94%', 'Success Rate'], 
  ['4.9★', 'User Rating'], 
  ['120+', 'Companies Covered']
];

/* ─── Mockups & Interactive Visuals ────────────────────────────────────── */

/**
 * 1. Right Hero Column - Interactive Live Interview Session Mockup
 */
const VoiceVisualizerMockup = () => {
  return (
    <div className="w-full max-w-[460px] bg-slate-950/80 border border-slate-800/80 rounded-2xl p-5 shadow-2xl backdrop-blur-md relative overflow-hidden font-sans text-left">
      {/* Top window bar */}
      <div className="flex items-center justify-between pb-4 border-b border-slate-800/60 mb-4">
        <div className="flex items-center gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full bg-rose-500/80" />
          <span className="w-2.5 h-2.5 rounded-full bg-amber-500/80" />
          <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/80" />
        </div>
        <div className="text-[10px] text-slate-500 font-mono tracking-widest uppercase">Live Session: Behavior Model</div>
        <div className="w-2.5 h-2.5 rounded bg-slate-800/50" />
      </div>

      {/* Main Grid: Interviewer Speech bubble and Voice Wave */}
      <div className="space-y-4">
        {/* Interviewer Profile Card */}
        <div className="flex items-center justify-between bg-white/[0.02] border border-white/[0.04] p-3 rounded-xl">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-full bg-gradient-to-br from-indigo-500 to-cyan-500 flex items-center justify-center font-black text-xs text-white shadow-lg shadow-indigo-500/20">
              AI
            </div>
            <div>
              <div className="text-xs font-bold text-slate-200">Interviewer AI (Sophia)</div>
              <div className="text-[10px] text-cyan-400 font-bold flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
                Speaking...
              </div>
            </div>
          </div>
          <div className="w-7 h-7 rounded-lg bg-slate-900 flex items-center justify-center border border-slate-800">
            <Volume2 size={13} className="text-slate-400" />
          </div>
        </div>

        {/* AI Question Speech bubble */}
        <div className="bg-slate-900/95 border border-slate-800/60 p-4 rounded-2xl text-[13px] text-slate-300 leading-relaxed shadow-inner">
          "Tell me about a time when you had to make a critical design decision under tight deadlines. How did you weigh the trade-offs?"
        </div>

        {/* Animated Voice Wave Visualizer */}
        <div className="flex items-center justify-center gap-1.5 py-6 bg-slate-900/40 rounded-xl border border-slate-900/60">
          {[12, 28, 48, 36, 16, 24, 40, 18, 8, 20, 32, 14].map((h, i) => (
            <motion.div
              key={i}
              animate={{ 
                height: [
                  `${h * 0.4}px`, 
                  `${h * 1.1}px`, 
                  `${h * 0.6}px`
                ] 
              }}
              transition={{
                duration: 1.1 + (i % 3) * 0.25,
                repeat: Infinity,
                repeatType: "reverse",
                ease: "easeInOut",
                delay: i * 0.04
              }}
              className="w-1.5 rounded-full bg-gradient-to-t from-indigo-500 via-purple-500 to-cyan-400"
            />
          ))}
        </div>

        {/* Floating User Response Preview */}
        <div className="flex items-start gap-3 bg-white/[0.01] border border-white/[0.03] p-3 rounded-xl">
          <div className="w-7 h-7 rounded-full bg-slate-800 flex items-center justify-center text-xs font-semibold text-slate-350 border border-slate-700/50">
            You
          </div>
          <div className="flex-1">
            <div className="text-[10px] font-bold text-slate-500">Your Answer (Transcribing...)</div>
            <div className="text-[12px] text-slate-350 italic mt-0.5">
              "We had to choose between a fully relational schema and a document store for our analytics pipeline..."
            </div>
          </div>
        </div>

        {/* Real-time feedback analytics metrics */}
        <div className="grid grid-cols-3 gap-2 pt-1 border-t border-slate-900">
          <div className="bg-slate-900/60 border border-slate-850 p-2 rounded-xl text-center">
            <div className="text-[9px] text-slate-500 uppercase tracking-wider font-bold">Pacing</div>
            <div className="text-[12px] font-bold text-emerald-400 mt-0.5">120 wpm</div>
          </div>
          <div className="bg-slate-900/60 border border-slate-850 p-2 rounded-xl text-center">
            <div className="text-[9px] text-slate-500 uppercase tracking-wider font-bold">Confidence</div>
            <div className="text-[12px] font-bold text-cyan-400 mt-0.5">High (88%)</div>
          </div>
          <div className="bg-slate-900/60 border border-slate-850 p-2 rounded-xl text-center">
            <div className="text-[9px] text-slate-500 uppercase tracking-wider font-bold">Clarity</div>
            <div className="text-[12px] font-bold text-indigo-400 mt-0.5">Excellent</div>
          </div>
        </div>
      </div>
    </div>
  );
};

/**
 * 2. Features Section - Monaco Code Editor & Live Feedback Mockup
 */
const CodeEditorMockup = () => {
  return (
    <div className="w-full max-w-[500px] bg-slate-950 border border-slate-800 rounded-2xl shadow-xl overflow-hidden text-left font-mono">
      {/* Header tab bar */}
      <div className="flex items-center justify-between px-4 py-3 bg-slate-900 border-b border-slate-950">
        <div className="flex items-center gap-2">
          <div className="flex gap-1.5 mr-2">
            <span className="w-2.5 h-2.5 rounded-full bg-rose-500/85" />
            <span className="w-2.5 h-2.5 rounded-full bg-amber-500/85" />
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/85" />
          </div>
          <div className="flex items-center gap-1.5 px-3 py-1 bg-slate-950 border border-slate-850 rounded-t-lg text-[11px] text-indigo-300 font-semibold border-b-transparent">
            <Code2 size={12} className="text-indigo-400" />
            solution.js
          </div>
        </div>
        <div className="text-[10px] text-slate-500 font-sans font-semibold uppercase tracking-wider flex items-center gap-1.5">
          <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-pulse" />
          Live Coding
        </div>
      </div>

      {/* Editor Content Area */}
      <div className="p-5 text-[12px] leading-relaxed text-slate-300 space-y-1 bg-slate-950">
        <div><span className="text-slate-700 mr-4 select-none">1</span><span className="text-purple-400 font-bold">function</span> <span className="text-blue-400">longestSubstring</span>(s) &#123;</div>
        <div><span className="text-slate-700 mr-4 select-none">2</span>  <span className="text-purple-400 font-bold">let</span> maxLen = <span className="text-amber-400">0</span>, start = <span className="text-amber-400">0</span>;</div>
        <div><span className="text-slate-700 mr-4 select-none">3</span>  <span className="text-purple-400 font-bold">const</span> seen = <span className="text-purple-400 font-bold">new</span> <span className="text-yellow-400">Map</span>();</div>
        <div><span className="text-slate-700 mr-4 select-none">4</span>  <span className="text-purple-400 font-bold">for</span> (<span className="text-purple-400 font-bold">let</span> end = <span className="text-amber-400">0</span>; end &lt; s.length; end++) &#123;</div>
        <div><span className="text-slate-700 mr-4 select-none">5</span>    <span className="text-purple-400 font-bold">if</span> (seen.<span className="text-blue-400">has</span>(s[end])) &#123;</div>
        <div><span className="text-slate-700 mr-4 select-none">6</span>      start = <span className="text-yellow-400">Math</span>.<span className="text-blue-400">max</span>(seen.<span className="text-blue-400">get</span>(s[end]) + <span className="text-amber-400">1</span>, start);</div>
        <div><span className="text-slate-700 mr-4 select-none">7</span>    &#125;</div>
        <div><span className="text-slate-700 mr-4 select-none">8</span>    seen.<span className="text-blue-400">set</span>(s[end], end);</div>
        <div><span className="text-slate-700 mr-4 select-none">9</span>    maxLen = <span className="text-yellow-400">Math</span>.<span className="text-blue-400">max</span>(maxLen, end - start + <span className="text-amber-400">1</span>);</div>
        <div><span className="text-slate-700 mr-4 select-none">10</span>  &#125;</div>
        <div><span className="text-slate-700 mr-4 select-none">11</span>  <span className="text-purple-400 font-bold">return</span> maxLen;</div>
        <div><span className="text-slate-700 mr-4 select-none">12</span>&#125;</div>
      </div>

      {/* Compiler output bar */}
      <div className="bg-slate-900 p-4 border-t border-slate-950 font-mono text-[11px]">
        <div className="text-slate-500 mb-1.5 flex items-center justify-between font-sans">
          <span>Compiler Terminal</span>
          <span className="text-emerald-400 font-bold">✓ 8/8 Tests Passed</span>
        </div>
        <div className="text-emerald-400 bg-slate-950 p-2.5 rounded border border-slate-800 flex items-center justify-between">
          <span>Test Case 3: s = "abcabcbb" (Expected: 3)</span>
          <span className="font-sans text-[10px] font-bold px-2 py-0.5 bg-emerald-500/10 text-emerald-400 rounded border border-emerald-500/20">PASSED</span>
        </div>
      </div>

      {/* AI Scorecard panel floating over the bottom */}
      <div className="bg-slate-900 border-t border-slate-800 p-4 font-sans text-slate-200 flex items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 font-bold text-sm">
            O(N)
          </div>
          <div>
            <div className="text-xs font-bold text-slate-200">Algorithmic Efficiency</div>
            <div className="text-[10px] text-slate-400 font-mono">Time Complexity Score: 98%</div>
          </div>
        </div>
        <div className="text-xs font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1.5 rounded-lg flex items-center gap-1">
          <CheckCircle2 size={13} />
          Optimal Solution
        </div>
      </div>
    </div>
  );
};

/**
 * 3. CTA Section - Success Milestone Milestone Graph
 */
const MilestoneGraph = () => {
  return (
    <div className="relative w-full max-w-[340px] h-[340px] flex items-center justify-center font-sans">
      {/* Center glowing orb */}
      <div className="absolute w-24 h-24 bg-indigo-500/10 rounded-full blur-2xl animate-pulse" />

      {/* Connecting Canvas Lines */}
      <svg className="absolute inset-0 w-full h-full -z-10 opacity-30 pointer-events-none" viewBox="0 0 340 340">
        <defs>
          <linearGradient id="line-grad" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#6366f1" />
            <stop offset="50%" stopColor="#a855f7" />
            <stop offset="100%" stopColor="#06b6d4" />
          </linearGradient>
        </defs>
        <path d="M 170 40 L 60 170 L 170 300 L 280 170 Z" fill="none" stroke="url(#line-grad)" strokeWidth="2" strokeDasharray="6,4" />
        <path d="M 170 40 L 170 300" fill="none" stroke="url(#line-grad)" strokeWidth="1" />
        <path d="M 60 170 L 280 170" fill="none" stroke="url(#line-grad)" strokeWidth="1" />
      </svg>

      {/* Floating Milestone Nodes */}
      <div className="absolute inset-0 flex flex-col justify-between items-center py-4">
        {/* Node 1: Start Prep */}
        <motion.div
          animate={{ y: [-3, 3, -3] }}
          transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
          className="bg-slate-900/90 border border-slate-800 px-4 py-2.5 rounded-2xl shadow-xl flex items-center gap-2"
        >
          <span className="text-base">🎯</span>
          <div className="text-left">
            <div className="text-[9px] text-slate-500 uppercase tracking-wider font-extrabold">Step 1</div>
            <div className="text-xs font-bold text-white">Join Platform</div>
          </div>
        </motion.div>

        {/* Middle row of nodes */}
        <div className="w-full flex justify-between px-2">
          {/* Node 2: Adaptive Practice */}
          <motion.div
            animate={{ y: [3, -3, 3] }}
            transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}
            className="bg-slate-900/90 border border-slate-800 px-4 py-2.5 rounded-2xl shadow-xl flex items-center gap-2"
          >
            <span className="text-base">🎙️</span>
            <div className="text-left">
              <div className="text-[9px] text-slate-500 uppercase tracking-wider font-extrabold">Step 2</div>
              <div className="Voice Practice text-xs font-bold text-white">AI Verbal Mock</div>
            </div>
          </motion.div>

          {/* Node 3: Performance Analysis */}
          <motion.div
            animate={{ y: [-4, 4, -4] }}
            transition={{ duration: 4.5, repeat: Infinity, ease: 'easeInOut' }}
            className="bg-slate-900/90 border border-slate-800 px-4 py-2.5 rounded-2xl shadow-xl flex items-center gap-2"
          >
            <span className="text-base">💻</span>
            <div className="text-left">
              <div className="text-[9px] text-slate-500 uppercase tracking-wider font-extrabold">Step 3</div>
              <div className="text-xs font-bold text-white">Live Coding</div>
            </div>
          </motion.div>
        </div>

        {/* Node 4: Placed at Top Company */}
        <motion.div
          animate={{ y: [3, -3, 3] }}
          transition={{ duration: 5.5, repeat: Infinity, ease: 'easeInOut' }}
          className="bg-cyan-500/10 border border-cyan-500/30 px-5 py-3 rounded-2xl shadow-lg shadow-cyan-500/10 flex items-center gap-2.5 backdrop-blur-md"
        >
          <span className="text-xl">🏆</span>
          <div className="text-left">
            <div className="text-[9px] text-cyan-400 uppercase tracking-wider font-extrabold">Step 4</div>
            <div className="text-xs font-black text-cyan-300">FAANG Offers</div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

/* ─── FAQ Item Accordion ─────────────────────────────────────────────────── */
const FAQItem = ({ q, a, i }) => {
  const [open, setOpen] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ delay: i * 0.05 }}
      className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300"
    >
      <button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between px-6 py-5 text-left gap-4 group">
        <span className="font-heading font-bold text-[16px] text-slate-800 group-hover:text-indigo-650 transition-colors">{q}</span>
        <motion.div animate={{ rotate: open ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown size={18} className="text-slate-400 flex-shrink-0" />
        </motion.div>
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
          >
            <div className="px-6 pb-5 text-[14px] text-slate-500 leading-relaxed border-t border-slate-100 pt-4 bg-slate-50/50">{a}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

/* ─── Landing Page ─────────────────────────────────────────────────────── */
const Landing = () => {
  const heroRef = useRef(null);
  const { scrollY } = useScroll();
  const heroY       = useTransform(scrollY, [0, 400], [0, -30]);

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-800 overflow-x-hidden relative z-0 font-sans">
      
      {/* ══════════════════════════════════════════════════════════
          SLICK DARK-MODE HERO (Gradient Mesh + Live Audio visualizer)
      ══════════════════════════════════════════════════════════ */}
      <div className="relative bg-slate-950 text-white overflow-hidden border-b border-slate-900 z-0">
        
        {/* Ambient glow mesh orbs */}
        <div className="absolute inset-0 pointer-events-none overflow-hidden">
          <motion.div
            animate={{ scale: [1, 1.2, 1], opacity: [0.25, 0.45, 0.25] }}
            transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
            className="absolute -top-60 -left-60 w-[700px] h-[700px] bg-indigo-650/40 bg-indigo-600/30 rounded-full blur-[130px]"
          />
          <motion.div
            animate={{ scale: [1.15, 1, 1.15], opacity: [0.2, 0.35, 0.2] }}
            transition={{ duration: 12, repeat: Infinity, ease: 'easeInOut', delay: 2 }}
            className="absolute top-40 -right-20 w-[600px] h-[600px] bg-cyan-500/25 rounded-full blur-[120px]"
          />
          <div className="absolute bottom-0 left-1/3 w-[500px] h-[500px] bg-purple-600/15 rounded-full blur-[140px]" />
        </div>

        {/* ══════════════════════════════════════════════════════════
            NAV
        ══════════════════════════════════════════════════════════ */}
        <motion.nav
          initial={{ y: -80, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.6, ease: 'easeOut' }}
          className="relative z-10 flex items-center justify-between px-8 py-5 border-b border-white/[0.06] bg-slate-950/40 backdrop-blur-md"
        >
          <Logo size={32} subtext="AI Interview Coach" textClassName="text-white" />
          <div className="hidden md:flex items-center gap-8 text-sm text-white/70">
            {['Features', 'Pricing', 'FAQ'].map((item) => (
              <a key={item} href={`#${item.toLowerCase()}`}
                className="relative hover:text-white transition-colors duration-200 group">
                {item}
                <span className="absolute -bottom-0.5 left-0 w-0 h-px bg-cyan-300 group-hover:w-full transition-all duration-300" />
              </a>
            ))}
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login" className="text-sm text-white/70 hover:text-white transition-colors px-3 py-2">Sign in</Link>
            <Link to="/register"
              className="flex items-center gap-2 bg-indigo-500 hover:bg-indigo-400 text-white text-sm font-bold px-5 py-2.5 rounded-xl transition-all shadow-md shadow-indigo-500/10 hover:shadow-indigo-500/30 hover:-translate-y-0.5">
              Get Started <ArrowRight size={14} />
            </Link>
          </div>
        </motion.nav>

        {/* ══════════════════════════════════════════════════════════
            HERO MAIN CONTENT
        ══════════════════════════════════════════════════════════ */}
        <motion.section
          ref={heroRef}
          style={{ y: heroY }}
          className="relative z-10 max-w-6xl mx-auto flex flex-col lg:flex-row items-center justify-between px-6 pt-16 pb-24 gap-16"
        >
          {/* Left Column: Heading, Subtitle & Buttons */}
          <div className="flex-[1.1] text-left flex flex-col items-start">
            
            {/* Pill Badge */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-white/10 bg-white/5 backdrop-blur-md text-xs text-indigo-300 font-bold uppercase tracking-wider mb-8"
            >
              <Sparkles size={12} className="text-cyan-300" />
              AI-Powered Interview Coach
            </motion.div>

            {/* Syne Heading */}
            <h1 className="font-heading text-4xl md:text-[58px] font-black leading-[1.05] tracking-tight mb-6">
              Ace Every Tech <br />
              Interview with <span className="text-cyan-300 relative inline-block bg-gradient-to-r from-cyan-300 via-indigo-300 to-purple-400 bg-clip-text text-transparent">AI Practice</span>
            </h1>

            {/* Body text */}
            <p className="text-[17px] text-slate-350 max-w-xl mb-10 leading-relaxed">
              Practice HR, DSA, System Design, and Behavioral interviews with an adaptive real-time AI interviewer.
              Receive compiler verification, confidence analysis, and structured improvement plans.
            </p>

            {/* CTA action buttons */}
            <div className="flex items-center gap-4 flex-wrap mb-14">
              <Link to="/register"
                className="group flex items-center gap-2.5 bg-indigo-500 hover:bg-indigo-400 text-white font-bold px-8 py-4 rounded-2xl text-[16px] transition-all shadow-xl shadow-indigo-500/20 hover:shadow-indigo-500/40 hover:-translate-y-0.5">
                Start Practicing Free
                <motion.span animate={{ x: [0, 4, 0] }} transition={{ duration: 1.2, repeat: Infinity }}>
                  <ArrowRight size={18} />
                </motion.span>
              </Link>
              <Link to="/login"
                className="flex items-center gap-2 bg-white/5 border border-white/10 hover:bg-white/10 text-white font-semibold px-8 py-4 rounded-2xl text-[16px] transition-all backdrop-blur-sm">
                <Play size={15} className="text-cyan-300 fill-cyan-300" /> Watch Demo
              </Link>
            </div>

            {/* Glassmorphic Stats bar inside dark hero */}
            <div className="w-full grid grid-cols-2 md:grid-cols-4 gap-6 bg-white/[0.02] border border-white/[0.05] p-6 rounded-2xl backdrop-blur-md shadow-2xl">
              {STATS.map(([val, label]) => (
                <div key={label} className="group">
                  <div className="font-heading text-2xl font-black text-white group-hover:text-cyan-300 transition-colors duration-300">{val}</div>
                  <div className="text-[11px] text-slate-400 mt-1 tracking-wide font-medium">{label}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Right Column: Audio & Dashboard Mockup */}
          <div className="flex-1 w-full relative flex items-center justify-center">
            {/* Soft glowing aura behind the mockup */}
            <div className="absolute w-72 h-72 bg-indigo-500/25 rounded-full blur-[80px] -z-10 animate-pulse" />
            <VoiceVisualizerMockup />
          </div>

        </motion.section>
      </div>

      {/* ══════════════════════════════════════════════════════════
          FEATURES SECTION
      ══════════════════════════════════════════════════════════ */}
      <section id="features" className="relative z-10 py-24 px-6 bg-white">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-xs text-slate-500 mb-4 uppercase tracking-widest font-semibold">
            Capabilities
          </div>
          <h2 className="font-heading text-4xl font-extrabold text-slate-900 mb-3">Designed for Premium Practice</h2>
          <p className="text-slate-500 max-w-xl mx-auto">One platform containing all evaluation engines required for modern engineering interviews.</p>
        </motion.div>

        {/* Feature Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto mb-28">
          {FEATURES.map(({ icon: Icon, title, desc, color }, i) => (
            <motion.div
              key={title}
              initial={{ opacity: 0, y: 20, scale: 0.98 }}
              whileInView={{ opacity: 1, y: 0, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.06, duration: 0.5 }}
              whileHover={{ y: -6, scale: 1.01 }}
              className="relative group rounded-2xl p-7 bg-white border border-slate-100 shadow-sm cursor-default transition-all duration-300 hover:border-indigo-200 hover:shadow-md hover:bg-slate-50/20"
            >
              {/* Card subtle border color sweep on hover */}
              <div className={`absolute -inset-px rounded-2xl bg-gradient-to-br ${color} opacity-0 group-hover:opacity-[0.04] transition-opacity duration-500 blur-xl`} />

              <div className={`relative w-12 h-12 rounded-2xl bg-gradient-to-br ${color} flex items-center justify-center mb-5 shadow-sm text-white`}>
                <Icon size={20} />
              </div>
              <div className="relative font-heading font-bold text-[17px] text-slate-800 mb-2 group-hover:text-indigo-650 transition-colors">{title}</div>
              <div className="relative text-[14px] text-slate-500 leading-relaxed">{desc}</div>
            </motion.div>
          ))}
        </div>

        {/* Split Feature Showcase - Mock Editor Illustration */}
        <div className="max-w-6xl mx-auto flex flex-col lg:flex-row items-center justify-between gap-16 mt-16 px-4">
          <div className="flex-1 text-left">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-xs text-slate-500 mb-4 uppercase tracking-widest font-semibold">
              Live Mocking
            </div>
            <h3 className="font-heading text-3xl font-extrabold text-slate-900 mb-4 leading-tight">Monaco-Powered Technical Coding rounds</h3>
            <p className="text-slate-500 leading-relaxed text-[15.5px] mb-6">
              Write, compile, and optimize algorithms inside an integrated coding environment. GPT-4o provides real-time complexity analysis (Big O) and feedback on edge cases.
            </p>
            <div className="space-y-4">
              {[
                'Full Monaco editor supporting JS, Python, C++, and Java',
                'Automatic hidden test-case evaluator',
                'Deep complexity scorer & code structure assessment'
              ].map(item => (
                <div key={item} className="flex items-center gap-3">
                  <div className="w-5 h-5 rounded-full bg-indigo-50 flex items-center justify-center flex-shrink-0">
                    <Check size={12} className="text-indigo-600 font-bold" />
                  </div>
                  <span className="text-[14px] text-slate-650 font-semibold">{item}</span>
                </div>
              ))}
            </div>
          </div>
          
          <div className="flex-1 relative flex items-center justify-center">
            {/* Glowing gradient background for mockup */}
            <div className="absolute w-80 h-80 bg-indigo-500/10 rounded-full blur-[80px] -z-10" />
            <CodeEditorMockup />
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          PRICING SECTION (Clean layout with hover glowing)
      ══════════════════════════════════════════════════════════ */}
      <section id="pricing" className="relative z-10 px-6 py-24 bg-slate-50 border-y border-slate-100">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-xs text-slate-500 mb-4 uppercase tracking-widest font-semibold">
            Pricing
          </div>
          <h2 className="font-heading text-4xl font-extrabold text-slate-900 mb-3">Transparent Plans</h2>
          <p className="text-slate-500">Pick a package that fits your preparation needs.</p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          {PRICING.map(({ plan, price, period, features, cta, highlight }, i) => (
            <motion.div
              key={plan}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.08 }}
              whileHover={{ y: -4 }}
              className={`relative rounded-2xl p-8 border bg-white transition-all duration-300 ${highlight
                ? 'border-indigo-500 shadow-xl shadow-indigo-500/5'
                : 'border-slate-200 hover:border-slate-350 hover:shadow-md'
              }`}
            >
              {highlight && (
                <>
                  <div className="absolute -inset-px rounded-2xl bg-gradient-to-br from-indigo-500/10 to-cyan-500/10 blur-xl -z-10" />
                  <div className="text-[10px] font-bold tracking-widest text-indigo-600 uppercase mb-4 flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-indigo-650 bg-indigo-600 animate-pulse" />
                    Recommended Plan
                  </div>
                </>
              )}
              <div className="font-heading font-bold text-xl text-slate-800 mb-2">{plan}</div>
              <div className="flex items-end gap-1 mb-6">
                <span className="font-heading text-5xl font-extrabold text-slate-900">{price}</span>
                <span className="text-slate-400 text-sm pb-1.5">{period}</span>
              </div>
              <div className="space-y-3.5 mb-8 border-t border-slate-100 pt-6">
                {features.map((f) => (
                  <div key={f} className="flex items-center gap-3 text-[13.5px]">
                    <div className={`w-4.5 h-4.5 rounded-full flex items-center justify-center flex-shrink-0 ${highlight ? 'bg-indigo-50' : 'bg-slate-50'}`}>
                      <Check size={11} className={highlight ? 'text-indigo-600 font-bold' : 'text-slate-400'} />
                    </div>
                    <span className="text-slate-650 font-medium">{f}</span>
                  </div>
                ))}
              </div>
              <Link
                to="/register"
                className={`block w-full text-center py-3.5 rounded-xl text-sm font-semibold transition-all shadow-sm ${highlight
                  ? 'bg-indigo-500 hover:bg-indigo-600 text-white font-bold hover:shadow-md'
                  : 'bg-slate-50 border border-slate-200 hover:bg-slate-100 text-slate-700'
                }`}
              >
                {cta}
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          FAQ SECTION
      ══════════════════════════════════════════════════════════ */}
      <section id="faq" className="relative z-10 px-6 py-24 max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-xs text-slate-500 mb-4 uppercase tracking-widest font-semibold">
            FAQ
          </div>
          <h2 className="font-heading text-4xl font-extrabold text-slate-900">Frequently Answered Questions</h2>
        </motion.div>
        <div className="space-y-4">
          {FAQS.map(({ q, a }, i) => <FAQItem key={i} q={q} a={a} i={i} />)}
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          CTA SECTION (Premium Dark Card + Connecting Milestone Visual)
      ══════════════════════════════════════════════════════════ */}
      <section className="relative z-10 px-8 py-20 max-w-5xl mx-auto mb-24 overflow-hidden rounded-3xl bg-slate-950 border border-slate-800 text-white shadow-2xl">
        {/* Glow bubbles */}
        <div className="absolute top-0 right-0 w-80 h-80 bg-indigo-500/10 rounded-full blur-[70px] pointer-events-none" />
        <div className="absolute -bottom-20 -left-20 w-80 h-80 bg-cyan-500/10 rounded-full blur-[70px] pointer-events-none" />

        <div className="flex flex-col lg:flex-row items-center justify-between gap-12 relative z-10">
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            className="flex-[1.2] text-left"
          >
            <div className="inline-flex items-center gap-2 text-3xl mb-4">🚀</div>
            <h2 className="font-heading text-4xl md:text-5xl font-black mb-4 leading-tight">
              Ready to land your<br />
              <span className="text-cyan-300 bg-gradient-to-r from-cyan-300 to-indigo-300 bg-clip-text text-transparent">dream career?</span>
            </h2>
            <p className="text-slate-400 mb-10 text-lg leading-relaxed">Join thousands of developers using InterviewAI Pro to build mock competency and master code reviews.</p>
            
            <Link
              to="/register"
              className="inline-flex items-center gap-3 bg-indigo-500 hover:bg-indigo-400 text-white font-bold px-10 py-5 rounded-2xl text-[17px] transition-all shadow-xl shadow-indigo-500/20 hover:shadow-indigo-500/40 hover:-translate-y-0.5"
            >
              Start Free Practice
              <motion.span animate={{ x: [0, 4, 0] }} transition={{ duration: 1, repeat: Infinity }}>
                <ArrowRight size={20} />
              </motion.span>
            </Link>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            className="flex-1 flex justify-center"
          >
            <MilestoneGraph />
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          FOOTER
      ══════════════════════════════════════════════════════════ */}
      <footer className="relative z-10 px-8 py-12 border-t border-slate-200 flex flex-col md:flex-row items-center justify-between gap-6 bg-white">
        <Logo size={28} subtext="Empowered Preparation" textClassName="text-slate-800" />
        <div className="flex gap-8 text-xs text-slate-500">
          {['Privacy Policy', 'Terms of Service', 'Contact Support'].map((item) => (
            <a key={item} href="#" className="hover:text-indigo-650 font-medium transition-colors">{item}</a>
          ))}
        </div>
        <div className="text-xs text-slate-400 font-medium">© 2025 InterviewAI Pro. All rights reserved.</div>
      </footer>
    </div>
  );
};

export default Landing;
